# Generated by Django 4.2.4 on 2023-08-22 13:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KategoriProduk',
            fields=[
                ('idKategori', models.AutoField(primary_key=True, serialize=False)),
                ('namaKategori', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Produk',
            fields=[
                ('idProduk', models.AutoField(primary_key=True, serialize=False)),
                ('namaProduk', models.CharField(max_length=100)),
                ('hargaProduk', models.FloatField()),
                ('kategori', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.kategoriproduk')),
            ],
        ),
    ]
